# 总倒计时秒数
#totalSeconds=1800
totalSeconds=1

# 主窗口位置
primaryStage.x=1170
primaryStage.y=47
# 主窗口尺寸
primaryStage.width=70
primaryStage.height=26
# 拖拽阈值
drag.threshold=5
# 主窗口透明度
primaryStage.opacity=0.8
# 主窗口置顶刷新间隔
alwaysOnTop.refreshMinutes=1


# 弹窗尺寸
show.width=1200
show.height=600
# 正计时几秒后弹窗
countupSeconds=1
# 强制弹窗显示秒数
showSeconds=20